const THEME_KEY='trade-wars-interface-theme-v1';

const themes=[
  {id:'command',icon:'◫',name:'Command Center',tag:'Original interface',description:'The clean global trading desk that started Trade Wars.',brand:'GLOBAL MARKETS SIM',views:{dashboard:'Command',markets:'Markets',intel:'World Intel',portfolio:'Portfolio'},titles:{dashboard:'Command Center',markets:'Global Markets',intel:'World Intel',portfolio:'Portfolio'},advance:'Advance Day',complete:'Campaign Complete',reset:'Reset Run',event:'WORLD EVENT',why:'WHY IS THIS MOVING?',status:'Simulation feed online',top:'GLOBAL TRADING DESK',context:({hub,day,event})=>`GLOBAL DESK  ·  ${hub}  ·  DAY ${day}  ·  ${event}`},
  {id:'situation',icon:'🌐',name:'The Situation Room',tag:'Geopolitical command map',description:'A crisis-room interface built around hotspots, routes, alerts, and world status.',brand:'GLOBAL SITUATION ROOM',views:{dashboard:'Situation',markets:'Markets',intel:'Alerts',portfolio:'Positions'},titles:{dashboard:'World Situation',markets:'Regional Markets',intel:'Active Intelligence',portfolio:'Strategic Positions'},advance:'Advance Situation',complete:'Situation Closed',reset:'New Scenario',event:'ACTIVE WORLD EVENT',why:'MARKET IMPACT ANALYSIS',status:'Global watch active',top:'WORLD OPERATIONS CENTER',context:({hub,day,event})=>`WORLD STATUS // HUB ${hub} // DAY ${day} // ACTIVE: ${event}`},
  {id:'terminal',icon:'📟',name:'1987 Trade Terminal',tag:'CRT institutional terminal',description:'Monochrome command-line energy, scanlines, terse market codes, and old-school desk software.',brand:'GLOBAL TRADE SYSTEM / 87',views:{dashboard:'SYS',markets:'MKT',intel:'WIRE',portfolio:'BOOK'},titles:{dashboard:'SYSTEM OVERVIEW',markets:'MARKET MATRIX',intel:'NEWS WIRE',portfolio:'POSITION BOOK'},advance:'EXEC NEXT.DAY',complete:'SESSION CLOSED',reset:'RESET SESSION',event:'WIRE FLASH',why:'TRACE PRICE MOVE',status:'HOST LINK: ONLINE',top:'TW/87 TERMINAL SESSION',context:({hub,day,event})=>`TW/87> NODE:${hub}  DAY:${String(day).padStart(2,'0')}  WIRE:${event}`},
  {id:'intel',icon:'🕵️',name:'Intelligence Desk',tag:'Analyst dossier room',description:'Briefing folders, redactions, analyst assessments, cables, and classified-style market files.',brand:'GLOBAL INTELLIGENCE DESK',views:{dashboard:'Briefing',markets:'Assets',intel:'Signals',portfolio:'Dossier'},titles:{dashboard:'Morning Briefing',markets:'Asset Assessment',intel:'Signal Traffic',portfolio:'Position Dossier'},advance:'Next Briefing',complete:'Case Closed',reset:'Open New File',event:'FLASH CABLE',why:'ANALYST ASSESSMENT',status:'Secure channel open',top:'TRADE INTELLIGENCE DIRECTORATE',context:({hub,day,event})=>`CASE ${String(day).padStart(3,'0')}  ·  DESK ${hub}  ·  DISTRIBUTION: TRADER  ·  ${event}`},
  {id:'freight',icon:'🚢',name:'Global Freight Empire',tag:'Ports, cargo, manifests',description:'Container-yard industrial UI where positions feel like cargo moving through world ports.',brand:'GLOBAL FREIGHT EMPIRE',views:{dashboard:'Port',markets:'Exchange',intel:'Dispatch',portfolio:'Cargo'},titles:{dashboard:'Port Control',markets:'Cargo Exchange',intel:'Dispatch Feed',portfolio:'Cargo Manifest'},advance:'Advance Watch',complete:'Voyage Complete',reset:'New Voyage',event:'PORT DISPATCH',why:'LANDED COST BREAKDOWN',status:'Port network online',top:'GLOBAL LOGISTICS CONTROL',context:({hub,day,cash})=>`MANIFEST // PORT ${hub} // WATCH ${day} // LIQUID CAPITAL ${cash}`},
  {id:'newspaper',icon:'📰',name:'Financial Newspaper',tag:'Daily printed edition',description:'Every turn feels like a new business-paper edition with headlines, columns, and market tables.',brand:'THE TRADE WARS LEDGER',views:{dashboard:'Front Page',markets:'Markets',intel:'World',portfolio:'Ledger'},titles:{dashboard:'Front Page',markets:'Markets & Commerce',intel:'World Dispatches',portfolio:'Investor Ledger'},advance:'Print Next Edition',complete:'Final Edition',reset:'New Run',event:'LEAD STORY',why:'WHAT MOVED THE MARKET?',status:'Evening edition desk',top:'BUSINESS · TRADE · WORLD MARKETS',context:({hub,day})=>`THE TRADE WARS LEDGER  ·  DAY ${day} EDITION  ·  DATELINE ${hub}`},
  {id:'news',icon:'📺',name:'Global News Network',tag:'24-hour market television',description:'Broadcast graphics, breaking-news lower thirds, market tickers, and a live control-room feel.',brand:'TWNN · GLOBAL BUSINESS',views:{dashboard:'Live Desk',markets:'Market Board',intel:'News Wire',portfolio:'Book'},titles:{dashboard:'Trade Wars Live',markets:'Global Market Board',intel:'Breaking News Wire',portfolio:'Portfolio Desk'},advance:'Next Broadcast',complete:'Broadcast Complete',reset:'Restart Coverage',event:'BREAKING NEWS',why:'MARKET EXPLAINER',status:'LIVE · worldwide',top:'TWNN LIVE',context:({hub,day,event})=>`LIVE  ●  ${hub}  |  DAY ${day}  |  BREAKING: ${event}`},
  {id:'travel',icon:'🗺️',name:"Trader's Travel Desk",tag:'Passport and dealbook',description:'A globe-trotting dealmaker interface of passport stamps, tickets, dispatches, and local quotes.',brand:'TRADER’S TRAVEL DESK',views:{dashboard:'Passport',markets:'Local Markets',intel:'Dispatches',portfolio:'Ledger'},titles:{dashboard:'Passport & Itinerary',markets:'Local Trading Desk',intel:'Dispatches From Abroad',portfolio:'Travel Ledger'},advance:'Board Next Day',complete:'Journey Complete',reset:'New Journey',event:'FIELD DISPATCH',why:'LOCAL PRICE NOTES',status:'Passport ready',top:'INDEPENDENT GLOBAL TRADER',context:({hub,day})=>`PASSPORT CONTROL  ·  CURRENT STAMP ${hub}  ·  JOURNEY DAY ${day}`},
  {id:'control',icon:'🏗️',name:'Supply Chain Control Tower',tag:'Network dependency view',description:'Industrial systems control with nodes, flows, bottlenecks, and downstream exposure thinking.',brand:'SUPPLY CHAIN CONTROL TOWER',views:{dashboard:'Network',markets:'Inputs',intel:'Alerts',portfolio:'Inventory'},titles:{dashboard:'Network Control',markets:'Input Markets',intel:'Network Alerts',portfolio:'Inventory Exposure'},advance:'Run Next Cycle',complete:'Cycle Complete',reset:'Reset Network',event:'NETWORK DISRUPTION',why:'DEPENDENCY TRACE',status:'Network telemetry live',top:'GLOBAL SUPPLY NETWORK',context:({hub,day,event})=>`NETWORK STATUS  ·  NODE ${hub}  ·  CYCLE ${day}  ·  ${event}`},
  {id:'briefcase',icon:'💼',name:'The Executive Briefcase',tag:'Private dealmaker desktop',description:'Leather, folders, deal sheets, briefing notes, and the feeling of running trades from a private office.',brand:'PRIVATE GLOBAL DEALBOOK',views:{dashboard:'Desk',markets:'Deals',intel:'Files',portfolio:'Book'},titles:{dashboard:'Executive Desk',markets:'Deal Sheet',intel:'Briefing Files',portfolio:'Private Book'},advance:'Next Deal Day',complete:'Book Closed',reset:'New Dealbook',event:'PRIORITY MEMO',why:'DEAL NOTE',status:'Private line connected',top:'EXECUTIVE TRADE OFFICE',context:({hub,day,cash})=>`DEAL BOOK  ·  ${hub}  ·  DAY ${day}  ·  AVAILABLE ${cash}`},
  {id:'exchange',icon:'📈',name:'Exchange Floor',tag:'Fast, loud market board',description:'Dense quote boards, session clocks, flashing moves, and a frantic floor-trading atmosphere.',brand:'TRADE WARS EXCHANGE',views:{dashboard:'Floor',markets:'Quotes',intel:'Wire',portfolio:'Positions'},titles:{dashboard:'Exchange Floor',markets:'Live Quote Board',intel:'Market Wire',portfolio:'Open Positions'},advance:'Close Session',complete:'Final Bell',reset:'New Session',event:'MARKET FLASH',why:'MOVE BREAKDOWN',status:'Market session open',top:'GLOBAL EXCHANGE FLOOR',context:({hub,day,event})=>`OPEN BOARD  ◆  ${hub}  ◆  SESSION ${day}  ◆  ${event}`},
  {id:'surveillance',icon:'🛰️',name:'Global Surveillance Network',tag:'Orbital market awareness',description:'Radar sweeps, satellite-grid styling, signal tracking, and geographically framed market intelligence.',brand:'GLOBAL SURVEILLANCE NETWORK',views:{dashboard:'Globe',markets:'Signals',intel:'Intercepts',portfolio:'Tracked Assets'},titles:{dashboard:'Global Observation',markets:'Economic Signals',intel:'Intercept Queue',portfolio:'Tracked Exposure'},advance:'Next Sweep',complete:'Sweep Complete',reset:'Clear Network',event:'SIGNAL DETECTED',why:'SIGNAL ATTRIBUTION',status:'Orbital feed locked',top:'ECONOMIC OBSERVATION GRID',context:({hub,day,event})=>`ORBITAL FEED  ·  NODE ${hub}  ·  SWEEP ${day}  ·  TRACK: ${event}`},
  {id:'arcade',icon:'🎮',name:'Trade Wars Arcade',tag:'Maximum game energy',description:'Chunky scoreboards, neon panels, round-based language, and deliberately playful arcade feedback.',brand:'TRADE WARS // ARCADE',views:{dashboard:'HQ',markets:'Shop',intel:'Alerts',portfolio:'Loadout'},titles:{dashboard:'PLAYER HQ',markets:'GLOBAL MARKET SHOP',intel:'WORLD ALERTS',portfolio:'PLAYER LOADOUT'},advance:'NEXT ROUND ▶',complete:'RUN COMPLETE',reset:'NEW GAME',event:'WORLD EVENT!',why:'WHY DID IT MOVE?',status:'PLAYER 1 READY',top:'GLOBAL TRADING ARCADE',context:({hub,day,cash})=>`PLAYER 1  ★  STAGE ${String(day).padStart(2,'0')}  ★  HUB ${hub}  ★  SCORE ${cash}`}
];

const byId=id=>themes.find(t=>t.id===id)||themes[0];
const storedTheme=()=>{try{return localStorage.getItem(THEME_KEY)||'command';}catch(e){return 'command';}};
const saveTheme=id=>{try{localStorage.setItem(THEME_KEY,id);}catch(e){}};
let currentTheme=byId(storedTheme());
let observer=null;
let syncQueued=false;
let drawerOpen=false;

const text=(selector,value)=>{const el=typeof selector==='string'?document.querySelector(selector):selector;if(el&&el.textContent!==value)el.textContent=value;};

function addStyles(){if(document.querySelector('link[href="themes.css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='themes.css';document.head.appendChild(link);}
function runtime(){const hub=(document.getElementById('currentHubCode')?.textContent||'NYC').trim();const day=(document.getElementById('dayValue')?.textContent||'1').split('/')[0].trim();const cash=(document.getElementById('cashValue')?.textContent||'$50,000').trim();const event=(document.getElementById('eventTitle')?.textContent||'World markets active').trim();return {hub,day,cash,event};}
function activeView(){return document.querySelector('[data-view-panel].is-active')?.dataset.viewPanel||'dashboard';}

function setNavLabels(theme){const icons={dashboard:'◫',markets:'↗',intel:'⌁',portfolio:'◎'};document.querySelectorAll('.nav-btn[data-view]').forEach(btn=>{const v=btn.dataset.view,label=theme.views[v]||v,html=`<span>${icons[v]||'•'}</span> ${label}`;if(btn.innerHTML!==html)btn.innerHTML=html;});document.querySelectorAll('.mobile-nav-btn[data-view]').forEach(btn=>{const v=btn.dataset.view,label=theme.views[v]||v,html=`<span>${icons[v]||'•'}</span><small>${label}</small>`;if(btn.innerHTML!==html)btn.innerHTML=html;});}

function syncThemeChrome(){const theme=currentTheme,view=activeView(),data=runtime();document.body.dataset.theme=theme.id;text('.brand small',theme.brand);text('.topbar .eyebrow',theme.top);text('#viewTitle',theme.titles[view]||'Trade Wars');text('.live-pill',theme.event);text('.sidebar-foot span:last-child',theme.status);text('#resetBtn',theme.reset);const next=document.getElementById('nextDayBtn');if(next){const wanted=next.disabled?theme.complete:`${theme.advance} →`;if(next.textContent.trim()!==wanted)next.textContent=wanted;}const whyEyebrow=document.querySelector('#whyModal .eyebrow');if(whyEyebrow&&whyEyebrow.textContent!==theme.why)whyEyebrow.textContent=theme.why;const strip=document.getElementById('themeContext');if(strip){const copy=theme.context(data);if(strip.textContent!==copy)strip.textContent=copy;}setNavLabels(theme);document.querySelectorAll('.theme-card').forEach(card=>{const chosen=card.dataset.themeChoice===theme.id;card.classList.toggle('is-selected',chosen);card.setAttribute('aria-pressed',chosen?'true':'false');});const name=document.getElementById('themeCurrentName');if(name)name.textContent=theme.name;}
function scheduleSync(){if(syncQueued)return;syncQueued=true;requestAnimationFrame(()=>{syncQueued=false;syncThemeChrome();});}
function applyTheme(id,{persist=true,close=true}={}){currentTheme=byId(id);if(persist)saveTheme(currentTheme.id);syncThemeChrome();if(close)closeDrawer();window.dispatchEvent(new CustomEvent('tradewars:themechange',{detail:{theme:currentTheme.id}}));}

function themeCard(theme){const button=document.createElement('button');button.type='button';button.className='theme-card';button.dataset.themeChoice=theme.id;button.innerHTML=`<span class="theme-preview preview-${theme.id}" aria-hidden="true"><i></i><b>${theme.icon}</b><em></em></span><span class="theme-card-copy"><strong>${theme.name}</strong><small>${theme.tag}</small><span>${theme.description}</span></span><span class="theme-check">✓</span>`;button.addEventListener('click',()=>applyTheme(theme.id));return button;}
function buildDrawer(){if(document.getElementById('themeDrawer'))return;const drawer=document.createElement('div');drawer.id='themeDrawer';drawer.className='theme-drawer-backdrop';drawer.setAttribute('aria-hidden','true');drawer.innerHTML=`<section class="theme-drawer" role="dialog" aria-modal="true" aria-labelledby="themeDrawerTitle"><div class="theme-drawer-head"><div><div class="eyebrow">INTERFACE SYSTEM</div><h2 id="themeDrawerTitle">Choose your Trade Wars world</h2><p>Same economy. Completely different desk.</p></div><button class="theme-close" id="themeClose" type="button" aria-label="Close theme selector">×</button></div><div class="theme-grid" id="themeGrid"></div></section>`;document.body.appendChild(drawer);const grid=drawer.querySelector('#themeGrid');themes.forEach(t=>grid.appendChild(themeCard(t)));drawer.querySelector('#themeClose').addEventListener('click',closeDrawer);drawer.addEventListener('click',e=>{if(e.target===drawer)closeDrawer();});}
function buildControls(){const actions=document.querySelector('.topbar-actions');if(actions&&!document.getElementById('themeBtn')){const btn=document.createElement('button');btn.id='themeBtn';btn.type='button';btn.className='ghost-btn theme-button';btn.setAttribute('aria-haspopup','dialog');btn.innerHTML='<span class="theme-button-icon">◈</span><span>Interface</span><small id="themeCurrentName">Command Center</small>';btn.addEventListener('click',openDrawer);actions.prepend(btn);}const main=document.querySelector('.main-content'),top=document.querySelector('.topbar');if(main&&top&&!document.getElementById('themeContext')){const strip=document.createElement('div');strip.id='themeContext';strip.className='theme-context';strip.setAttribute('aria-live','polite');top.after(strip);}if(!document.getElementById('themeAmbient')){const ambient=document.createElement('div');ambient.id='themeAmbient';ambient.className='theme-ambient';ambient.setAttribute('aria-hidden','true');ambient.innerHTML='<i class="ambient-a"></i><i class="ambient-b"></i><i class="ambient-c"></i>';document.body.prepend(ambient);}}
function openDrawer(){const drawer=document.getElementById('themeDrawer');if(!drawer)return;drawerOpen=true;drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('theme-picker-open');const selected=drawer.querySelector('.theme-card.is-selected')||drawer.querySelector('.theme-card');selected?.focus();}
function closeDrawer(){const drawer=document.getElementById('themeDrawer');if(!drawer||!drawerOpen)return;drawerOpen=false;drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('theme-picker-open');document.getElementById('themeBtn')?.focus();}
function observeGame(){if(observer)return;const app=document.getElementById('app');if(!app)return;observer=new MutationObserver(scheduleSync);observer.observe(app,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','disabled']});}

export function initThemes(){addStyles();buildDrawer();buildControls();syncThemeChrome();observeGame();document.addEventListener('click',e=>{if(e.target.closest('[data-view], [data-jump], #nextDayBtn, .hub-travel, .buy, .sell'))scheduleSync();},true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawerOpen)closeDrawer();});window.addEventListener('hashchange',scheduleSync);}
export {themes,applyTheme};
